 export const topTrendingProducts = [
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/chips.png"),
    Title: "Jelly beans exxotics",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "18.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/juice.png"),
    Title: "Growers cider",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "4.0",
    Amount: "5.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/mockupgraphs.png"),
    Title: "Fresh grapes",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "6.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "4",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/tomatoketchup.png"),
    Title: "Heinz tomato ketchup",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "5.0",
    Amount: "9.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/watermelonJuice.png"),
    Title: "Sunstar Fresh Melon Juice",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "3.5",
    Amount: "12.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "3",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/chips.png"),
    Title: "Jelly beans exxotics",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "18.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/juice.png"),
    Title: "Growers cider",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "4.0",
    Amount: "5.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/mockupgraphs.png"),
    Title: "Fresh grapes",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "6.00",
    Sold: "Sold: 30/40",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "4",
    DiscountAmount: "8.00",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/tomatoketchup.png"),
    Title: "Heinz tomato ketchup",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "5.0",
    Amount: "9.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/watermelonJuice.png"),
    Title: "Sunstar Fresh Melon Juice",
    Image: require("../assets/Images/Vector13.png"),
    Unit: "1 UNIT",
    Point: "3.5",
    Amount: "12.00",
    Sold: "Sold: 30/40",
    DiscountAmount: "8.00",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "3",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },

  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/brittany.png"),
    Title: "Pacific barista beverage",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "4.5",
    Amount: "12.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 30/40",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-35%",
    ProductImage: require("../assets/Images/tylerNix.png"),
    Title: "Kombucha local lilikoi",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "4.0",
    Amount: "12.00",
    DiscountAmount: "6.00",
    Sold: "Sold: 9/25",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "4",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-15%",
    ProductImage: require("../assets/Images/olga.png"),
    Title: "Cheese flavoured Lays",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "4.5",
    Amount: "12.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 12/60",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-39%",
    ProductImage: require("../assets/Images/madalyn.png"),
    Title: "Oat milk barista",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "5.0",
    Amount: "12.00",
    DiscountAmount: "5.00",
    Sold: "Sold: 12/35",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/elsa.png"),
    Title: "Dr. raw relax hearts",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "3.5",
    Amount: "13.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "6",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },

  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-25%",
    ProductImage: require("../assets/Images/brittany.png"),
    Title: "Pacific barista beverage",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "4.5",
    Amount: "12.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 30/40",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-35%",
    ProductImage: require("../assets/Images/tylerNix.png"),
    Title: "Kombucha local lilikoi",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "4.0",
    Amount: "12.00",
    DiscountAmount: "6.00",
    Sold: "Sold: 9/25",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "4",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-15%",
    ProductImage: require("../assets/Images/olga.png"),
    Title: "Cheese flavoured Lays",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "4.5",
    Amount: "12.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 12/60",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-39%",
    ProductImage: require("../assets/Images/madalyn.png"),
    Title: "Oat milk barista",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "5.0",
    Amount: "12.00",
    DiscountAmount: "5.00",
    Sold: "Sold: 12/35",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/elsa.png"),
    Title: "Dr. raw relax hearts",
    Unit: "1 UNIT",
    Image: require("../assets/Images/Vector13.png"),
    Point: "3.5",
    Amount: "13.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "6",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },

  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/jar.png"),
    Title: "Amber Pure Honey",
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "18.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/avocado.png"),
    Title: "Fresh Local Avocado",
    Unit: "1 KG",
    Point: "4.0",
    Amount: "10.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "4",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/pharma.png"),
    Title: "Pharma Cashew Butter",
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "19.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/milk.png"),
    Title: "Pure Dairy Milk",
    Unit: "1 UNIT",
    Point: "5.0",
    Amount: "8.00",
    Sold: "Sold: 5/25",
    DiscountAmount: "8.00",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/deva.png"),
    Title: "Suzane Creamy Cupcake",
    Unit: "1 UNIT",
    Point: "3.5",
    Amount: "14.00",
    Sold: "Sold: 5/25",
    DiscountAmount: "8.00",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "6",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/jar.png"),
    Title: "Amber Pure Honey",
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "18.00",
    Sold: "Sold: 5/25",
    DiscountAmount: "8.00",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/avocado.png"),
    Title: "Fresh Local Avocado",
    Unit: "1 KG",
    Point: "4.0",
    Amount: "10.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "4",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/pharma.png"),
    Title: "Pharma Cashew Butter",
    Unit: "1 UNIT",
    Point: "4.5",
    Amount: "19.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/milk.png"),
    Title: "Pure Dairy Milk",
    Unit: "1 UNIT",
    Point: "5.0",
    Amount: "8.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "2",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
  {
    isDiscountAvailable: false,
    isHeartIcon: false,
    DiscountPercentage: "-12%",
    ProductImage: require("../assets/Images/deva.png"),
    Title: "Suzane Creamy Cupcake",
    Unit: "1 UNIT",
    Point: "3.5",
    Amount: "14.00",
    DiscountAmount: "8.00",
    Sold: "Sold: 5/25",
    Image: require("../assets/Images/Vector13.png"),
    SubImage: require("../assets/Images/Vector10.png"),
    Count: "6",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",
  },
];

  export const trendingProducts = [
    {
        ProductImage: require("../assets/Images/chips.png"),
        Title: "Jelly beans exxotics",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",

    },
    {
        ProductImage: require("../assets/Images/juice.png"),
        Title: "Growers cider",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "12.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
    },
    {
        ProductImage: require("../assets/Images/tomatoketchup.png"),
        Title: "Heinz tomato ketchup",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",


    },
    {
        ProductImage: require("../assets/Images/chips.png"),
        Title: "Jelly beans exxotics",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",


    },
    {
        ProductImage: require("../assets/Images/mockupgraphs.png"),
        Title: "Fresh grapes",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        DiscountAmount: "8.00",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",


    },
    {
        
        ProductImage: require("../assets/Images/tomatoketchup.png"),
        Title: "Heinz tomato ketchup",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "5.0",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/watermelonJuice.png"),
        Title: "Sunstar Fresh Melon Juice",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "3.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "3",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
        ProductImage: require("../assets/Images/brittany.png"),
        Title: "Pacific barista beverage",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/tylerNix.png"),
        Title: "Kombucha local lilikoi",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.0",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/olga.png"),
        Title: "Cheese flavoured Lays",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/madalyn.png"),
        Title: "Oat milk barista",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "12.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/elsa.png"),
        Title: "Dr. raw relax hearts",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "3.5",
        DiscountAmount: "13.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
    
        ProductImage: require("../assets/Images/brittany.png"),
        Title: "Pacific barista beverage",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "12.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        
        ProductImage: require("../assets/Images/tylerNix.png"),
        Title: "Kombucha local lilikoi",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.0",
        DiscountAmount: "15.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/olga.png"),
        Title: "Cheese flavoured Lays",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/madalyn.png"),
        Title: "Oat milk barista",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/elsa.png"),
        Title: "Dr. raw relax hearts",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "3.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
       
        ProductImage: require("../assets/Images/jar.png"),
        Title: "Amber Pure Honey",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "4.5",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/avocado.png"),
        Title: "Fresh Local Avocado",
        Unit: "1 KG",
        isHeartIcon: false,
        Point: "4.0",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/pharma.png"),
        Title: "Pharma Cashew Butter",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "4.5",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/milk.png"),
        Title: "Pure Dairy Milk",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "5.0",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/deva.png"),
        Title: "Suzane Creamy Cupcake",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "3.5",
        DiscountAmount: "13.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/jar.png"),
        Title: "Amber Pure Honey",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "4.5",
        DiscountAmount: "70.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/avocado.png"),
        Title: "Fresh Local Avocado",
        Unit: "1 KG",
        isHeartIcon: false,
        Point: "4.0",
        DiscountAmount: "16.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/pharma.png"),
        Title: "Pharma Cashew Butter",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "4.5",
        DiscountAmount: "19.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        
        ProductImage: require("../assets/Images/milk.png"),
        Title: "Pure Dairy Milk",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "5.0",
        DiscountAmount: "19.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/deva.png"),
        Title: "Suzane Creamy Cupcake",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "3.5",
        DiscountAmount: "19.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },

];

  export const bestSellingProducts = [
    {
        ProductImage: require("../assets/Images/chips.png"),
        Title: "Jelly beans exxotics",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",

    },
    {
        ProductImage: require("../assets/Images/juice.png"),
        Title: "Growers cider",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
    },
    {
        ProductImage: require("../assets/Images/tomatoketchup.png"),
        Title: "Heinz tomato ketchup",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",


    },
    {
        ProductImage: require("../assets/Images/chips.png"),
        Title: "Jelly beans exxotics",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",


    },
    {
        ProductImage: require("../assets/Images/mockupgraphs.png"),
        Title: "Fresh grapes",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        DiscountAmount: "8.00",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",


    },
    {
        
        ProductImage: require("../assets/Images/tomatoketchup.png"),
        Title: "Heinz tomato ketchup",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/watermelonJuice.png"),
        Title: "Sunstar Fresh Melon Juice",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "3.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "3",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
        ProductImage: require("../assets/Images/brittany.png"),
        Title: "Pacific barista beverage",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/tylerNix.png"),
        Title: "Kombucha local lilikoi",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/olga.png"),
        Title: "Cheese flavoured Lays",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/madalyn.png"),
        Title: "Oat milk barista",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/elsa.png"),
        Title: "Dr. raw relax hearts",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "3.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
    
        ProductImage: require("../assets/Images/brittany.png"),
        Title: "Pacific barista beverage",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        
        ProductImage: require("../assets/Images/tylerNix.png"),
        Title: "Kombucha local lilikoi",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/olga.png"),
        Title: "Cheese flavoured Lays",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/madalyn.png"),
        Title: "Oat milk barista",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "5.0",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/elsa.png"),
        Title: "Dr. raw relax hearts",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Image: require("../assets/Images/Vector13.png"),
        Point: "3.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
       
        ProductImage: require("../assets/Images/jar.png"),
        Title: "Amber Pure Honey",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "4.5",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/avocado.png"),
        Title: "Fresh Local Avocado",
        Unit: "1 KG",
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/pharma.png"),
        Title: "Pharma Cashew Butter",
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/milk.png"),
        Title: "Pure Dairy Milk",
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/deva.png"),
        Title: "Suzane Creamy Cupcake",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "3.5",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/jar.png"),
        Title: "Amber Pure Honey",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "4.5",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/avocado.png"),
        Title: "Fresh Local Avocado",
        Unit: "1 KG",
        isHeartIcon: false,
        Point: "4.0",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/pharma.png"),
        Title: "Pharma Cashew Butter",
        Unit: "1 UNIT",
        isHeartIcon: false,
        Point: "4.5",
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        
        ProductImage: require("../assets/Images/milk.png"),
        Title: "Pure Dairy Milk",
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/deva.png"),
        Title: "Suzane Creamy Cupcake",
        Unit: "1 UNIT",
        Point: "3.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
];

 export const justLandedItems = [
    {
        ProductImage: require("../assets/Images/chips.png"),
        Title: "Jelly beans exxotics",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",

    },
    {
        ProductImage: require("../assets/Images/juice.png"),
        Title: "Growers cider",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
    },
    {
        ProductImage: require("../assets/Images/tomatoketchup.png"),
        Title: "Heinz tomato ketchup",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",


    },
    {
        ProductImage: require("../assets/Images/chips.png"),
        Title: "Jelly beans exxotics",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
    Count: "1",
    AddImage: require("../assets/Images/Vector11.png"),
    AddToCart: "Add To Cart",


    },
    {
        ProductImage: require("../assets/Images/mockupgraphs.png"),
        Title: "Fresh grapes",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        DiscountAmount: "8.00",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",


    },
    {
        
        ProductImage: require("../assets/Images/tomatoketchup.png"),
        Title: "Heinz tomato ketchup",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/watermelonJuice.png"),
        Title: "Sunstar Fresh Melon Juice",
        Image: require("../assets/Images/Vector13.png"),
        Unit: "1 UNIT",
        Point: "3.5",
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "3",
        isHeartIcon: false,
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
        ProductImage: require("../assets/Images/brittany.png"),
        Title: "Pacific barista beverage",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/tylerNix.png"),
        Title: "Kombucha local lilikoi",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/olga.png"),
        Title: "Cheese flavoured Lays",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/madalyn.png"),
        Title: "Oat milk barista",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/elsa.png"),
        Title: "Dr. raw relax hearts",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "3.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
    
        ProductImage: require("../assets/Images/brittany.png"),
        Title: "Pacific barista beverage",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        
        ProductImage: require("../assets/Images/tylerNix.png"),
        Title: "Kombucha local lilikoi",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/olga.png"),
        Title: "Cheese flavoured Lays",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/madalyn.png"),
        Title: "Oat milk barista",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/elsa.png"),
        Title: "Dr. raw relax hearts",
        Unit: "1 UNIT",
        Image: require("../assets/Images/Vector13.png"),
        Point: "3.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
    
      {
       
        ProductImage: require("../assets/Images/jar.png"),
        Title: "Amber Pure Honey",
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/avocado.png"),
        Title: "Fresh Local Avocado",
        Unit: "1 KG",
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/pharma.png"),
        Title: "Pharma Cashew Butter",
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/milk.png"),
        Title: "Pure Dairy Milk",
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        ProductImage: require("../assets/Images/deva.png"),
        Title: "Suzane Creamy Cupcake",
        Unit: "1 UNIT",
        Point: "3.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/jar.png"),
        Title: "Amber Pure Honey",
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "1",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/avocado.png"),
        Title: "Fresh Local Avocado",
        Unit: "1 KG",
        Point: "4.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "4",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
    
        ProductImage: require("../assets/Images/pharma.png"),
        Title: "Pharma Cashew Butter",
        Unit: "1 UNIT",
        Point: "4.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
        
        ProductImage: require("../assets/Images/milk.png"),
        Title: "Pure Dairy Milk",
        Unit: "1 UNIT",
        Point: "5.0",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "2",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
      {
       
        ProductImage: require("../assets/Images/deva.png"),
        Title: "Suzane Creamy Cupcake",
        Unit: "1 UNIT",
        Point: "3.5",
        isHeartIcon: false,
        DiscountAmount: "8.00",
        Image: require("../assets/Images/Vector13.png"),
        SubImage: require("../assets/Images/Vector10.png"),
        Count: "6",
        AddImage: require("../assets/Images/Vector11.png"),
        AddToCart: "Add To Cart",
      },
];


