import category from "../Config/CategoryConfig";

export const topTrendingProducts = [
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    amount: "18.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/juice.png"),
    title: "Growers cider",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.0",
    amount: "5.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/mockupgraphs.png"),
    title: "Fresh grapes",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    amount: "6.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "5.0",
    amount: "9.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/watermelonJuice.png"),
    title: "Sunstar Fresh Melon Juice",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "3.5",
    amount: "12.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "3",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    amount: "18.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/juice.png"),
    title: "Growers cider",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.0",
    amount: "5.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/mockupgraphs.png"),
    title: "Fresh grapes",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    amount: "6.00",
    sold: "Sold: 30/40",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    discountAmount: "8.00",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "5.0",
    amount: "9.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/watermelonJuice.png"),
    title: "Sunstar Fresh Melon Juice",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "3.5",
    amount: "12.00",
    sold: "Sold: 30/40",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "3",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    amount: "12.00",
    discountAmount: "8.00",
    sold: "Sold: 30/40",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-35%",
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    amount: "12.00",
    discountAmount: "6.00",
    sold: "Sold: 9/25",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-15%",
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    amount: "12.00",
    discountAmount: "8.00",
    sold: "Sold: 12/60",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-39%",
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    amount: "12.00",
    discountAmount: "5.00",
    sold: "Sold: 12/35",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    amount: "13.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-25%",
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    amount: "12.00",
    discountAmount: "8.00",
    sold: "Sold: 30/40",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-35%",
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    amount: "12.00",
    discountAmount: "6.00",
    sold: "Sold: 9/25",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-15%",
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    amount: "12.00",
    discountAmount: "8.00",
    sold: "Sold: 12/60",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-39%",
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    amount: "12.00",
    discountAmount: "5.00",
    sold: "Sold: 12/35",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    amount: "13.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    point: "4.5",
    amount: "18.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    point: "4.0",
    amount: "10.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    point: "4.5",
    amount: "19.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    point: "5.0",
    amount: "8.00",
    sold: "Sold: 5/25",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    point: "3.5",
    amount: "14.00",
    sold: "Sold: 5/25",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    point: "4.5",
    amount: "18.00",
    sold: "Sold: 5/25",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    point: "4.0",
    amount: "10.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    point: "4.5",
    amount: "19.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    point: "5.0",
    amount: "8.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    isDiscountavailable: false,
    isHearticon: false,
    discountPercentage: "-12%",
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    point: "3.5",
    amount: "14.00",
    discountAmount: "8.00",
    sold: "Sold: 5/25",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
];

export const trendingProducts = [
  {
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/juice.png"),
    title: "Growers cider",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.0",
    isHearticon: false,
    discountAmount: "12.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/mockupgraphs.png"),
    title: "Fresh grapes",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    discountAmount: "8.00",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    isHearticon: false,
    point: "5.0",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/watermelonJuice.png"),
    title: "Sunstar Fresh Melon Juice",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    isHearticon: false,
    point: "3.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "3",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 2,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 2,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addToCart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    isHearticon: false,
    discountAmount: "12.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    discountAmount: "13.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "12.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 2,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    discountAmount: "15.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    point: "4.5",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    isHearticon: false,
    point: "4.0",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    isHearticon: false,
    point: "4.5",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    isHearticon: false,
    point: "5.0",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    point: "3.5",
    discountAmount: "13.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    point: "4.5",
    discountAmount: "70.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    isHearticon: false,
    point: "4.0",
    discountAmount: "16.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    isHearticon: false,
    point: "4.5",
    discountAmount: "19.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    isHearticon: false,
    point: "5.0",
    discountAmount: "19.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    point: "3.5",
    discountAmount: "19.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
];

export const bestSellingProducts = [
  {
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/juice.png"),
    title: "Growers cider",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/mockupgraphs.png"),
    title: "Fresh grapes",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    discountAmount: "8.00",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/watermelonJuice.png"),
    title: "Sunstar Fresh Melon Juice",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "3.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "3",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    isHearticon: false,
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    point: "4.5",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    point: "3.5",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    isHearticon: false,
    point: "4.5",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    isHearticon: false,
    point: "4.0",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    isHearticon: false,
    point: "4.5",
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    point: "3.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
];

export const justLandedItems = [
  {
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/juice.png"),
    title: "Growers cider",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/chips.png"),
    title: "Jelly beans exxotics",
    categoryId: 3,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/mockupgraphs.png"),
    title: "Fresh grapes",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    discountAmount: "8.00",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tomatoketchup.png"),
    title: "Heinz tomato ketchup",
    categoryId: 1,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/watermelonJuice.png"),
    title: "Sunstar Fresh Melon Juice",
    categoryId: 2,
    image: require("../assets/Images/Vector13.png"),
    unit: "1 UNIT",
    point: "3.5",
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "3",
    isHearticon: false,
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/brittany.png"),
    title: "Pacific barista beverage",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/tylerNix.png"),
    title: "Kombucha local lilikoi",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/olga.png"),
    title: "Cheese flavoured Lays",
    categoryId: 3,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/madalyn.png"),
    title: "Oat milk barista",
    categoryId: 2,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/elsa.png"),
    title: "Dr. raw relax hearts",
    categoryId: 6,
    unit: "1 UNIT",
    image: require("../assets/Images/Vector13.png"),
    point: "3.5",
    isHearticon: false,
    discountAmount: "8.00",
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },

  {
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    point: "3.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/jar.png"),
    title: "Amber Pure Honey",
    categoryId: 3,
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "1",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/avocado.png"),
    title: "Fresh Local Avocado",
    categoryId: 1,
    unit: "1 KG",
    point: "4.0",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "4",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/pharma.png"),
    title: "Pharma Cashew Butter",
    categoryId: 4,
    unit: "1 UNIT",
    point: "4.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/milk.png"),
    title: "Pure Dairy Milk",
    categoryId: 2,
    unit: "1 UNIT",
    point: "5.0",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "2",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
  {
    productImage: require("../assets/Images/deva.png"),
    title: "Suzane Creamy Cupcake",
    categoryId: 3,
    unit: "1 UNIT",
    point: "3.5",
    isHearticon: false,
    discountAmount: "8.00",
    image: require("../assets/Images/Vector13.png"),
    subImage: require("../assets/Images/Vector10.png"),
    count: "6",
    addImage: require("../assets/Images/Vector11.png"),
    addTocart: "Add To Cart",
  },
];
